"""公開配方目錄與追蹤創作者

user_recipes.is_public 與既有的 share_token 是兩件不同的事：
權杖分享是「知道網址的人看得到」，公開目錄是「所有人都找得到」。
既有配方一律預設為未公開，不會因為這次遷移而突然被列出。

follows 以 (follower_id, followee_id) 唯一索引擋掉重複追蹤，
並以 CHECK 擋掉追蹤自己——兩者都在資料庫層，不倚賴應用層先查再寫。

Revision ID: 2ac07240bc51
Revises: 2fd20abe0256
Create Date: 2026-09-07 15:21:35.727151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac07240bc51'
down_revision: Union[str, None] = '2fd20abe0256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> followee_id', name='ck_follow_not_self'),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followee_id', name='uq_follow_pair')
    )
    op.create_index(op.f('ix_follows_followee_id'), 'follows', ['followee_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.add_column('user_recipes', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_recipes', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_recipes_is_public'), 'user_recipes', ['is_public'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_recipes_is_public'), table_name='user_recipes')
    op.drop_column('user_recipes', 'published_at')
    op.drop_column('user_recipes', 'is_public')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_followee_id'), table_name='follows')
    op.drop_table('follows')
    # ### end Alembic commands ###
