"""add user recipe versions

Revision ID: 7657080bfac0
Revises: 9795e1866afc
Create Date: 2026-09-04 13:55:35.145493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7657080bfac0'
down_revision: Union[str, None] = '9795e1866afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recipe_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['user_recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_recipe_versions_recipe_id'), 'user_recipe_versions', ['recipe_id'], unique=False)
    op.create_index('ix_user_recipe_versions_recipe_version', 'user_recipe_versions', ['recipe_id', 'version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_recipe_versions_recipe_version', table_name='user_recipe_versions')
    op.drop_index(op.f('ix_user_recipe_versions_recipe_id'), table_name='user_recipe_versions')
    op.drop_table('user_recipe_versions')
    # ### end Alembic commands ###
