"""add recipe ratings and comments

Revision ID: 826b36584f39
Revises: 7657080bfac0
Create Date: 2026-09-04 14:03:13.234468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826b36584f39'
down_revision: Union[str, None] = '7657080bfac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['user_recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_comments_created_at'), 'recipe_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_recipe_comments_recipe_id'), 'recipe_comments', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_comments_user_id'), 'recipe_comments', ['user_id'], unique=False)
    op.create_table('recipe_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['user_recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ratings_recipe_id'), 'recipe_ratings', ['recipe_id'], unique=False)
    op.create_index('ix_recipe_ratings_recipe_user', 'recipe_ratings', ['recipe_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_recipe_ratings_user_id'), 'recipe_ratings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ratings_user_id'), table_name='recipe_ratings')
    op.drop_index('ix_recipe_ratings_recipe_user', table_name='recipe_ratings')
    op.drop_index(op.f('ix_recipe_ratings_recipe_id'), table_name='recipe_ratings')
    op.drop_table('recipe_ratings')
    op.drop_index(op.f('ix_recipe_comments_user_id'), table_name='recipe_comments')
    op.drop_index(op.f('ix_recipe_comments_recipe_id'), table_name='recipe_comments')
    op.drop_index(op.f('ix_recipe_comments_created_at'), table_name='recipe_comments')
    op.drop_table('recipe_comments')
    # ### end Alembic commands ###
