"""add user_recipes table

Revision ID: 9795e1866afc
Revises: 50af3f3d640b
Create Date: 2026-09-04 13:38:13.112417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9795e1866afc'
down_revision: Union[str, None] = '50af3f3d640b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_recipes_share_token'), 'user_recipes', ['share_token'], unique=True)
    op.create_index(op.f('ix_user_recipes_slug'), 'user_recipes', ['slug'], unique=True)
    op.create_index(op.f('ix_user_recipes_user_id'), 'user_recipes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_recipes_user_id'), table_name='user_recipes')
    op.drop_index(op.f('ix_user_recipes_slug'), table_name='user_recipes')
    op.drop_index(op.f('ix_user_recipes_share_token'), table_name='user_recipes')
    op.drop_table('user_recipes')
    # ### end Alembic commands ###
